title: Yunxuan Wang's Homepage
page-top-title: Yunxuan Wang
top-section-bg-text: Mathematics and Applied Mathematics
home-subtitle: Yunxuan Wang&ensp;|&ensp;王云萱
copyright-text: '&copy; Yunxuan Wang 2024. All Rights Reserved.'
